server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/robbertvdzon/config-repo/
          searchPaths: smoker-backend
          username: vdzon-config
          password: hJdyUIdos84dMNp(7
